name: timestamp
on:
  push:
    branches:
      - main
    paths:
      - '*.md'

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
        with: 
          fetch-depth: 1

      - name: Find changed markdown files and modify the time stamp
        run: |
          changed_mds=$(git diff --name-only | grep *.md)
          sed -i "s/Modified:.*/Modified: $(date +'%F %H:%I')/" $changed_mds
        shell: bash 
          
      - name: Commit changes
        run: |
          git config --global user.name "Isaac De Vlugt"
          git config --global user.email "isaac@xanadu.ai"
          git commit -am "Modified the timestamp in the updated blog posts"
          git push
