name: timestamp
on:
  push:
    branches:
      - main
    paths:
      - '*.md'

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Find changed markdown files and modify the time stamp
        run: sh ./timestamp.sh

      - name: Commit changes
        run: |
          git config --global user.name "Isaac De Vlugt"
          git config --global user.email "isaac@xanadu.ai"
          git commit -am "Modified the timestamp in the updated blog posts"
          git push
